using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Tiendita_Moreno.BussinessEntities
{
    public class Product
    {

        /// <summary>
        /// Is the Primary Key of the Table
        /// </summary>
        [Key]
        public int Id { get; set; }

        /// <summary>
        /// It is a small description about the product
        /// </summary>
        [Required(ErrorMessage = "The field Description is required")]
        [StringLength(50, ErrorMessage = "The field Description must have max length of 50 Characteres")]
        [DataType(DataType.Text, ErrorMessage = "The field Description must be a string")]
        public string Description { get; set; }

        /// <summary>
        /// It is the product identifier
        /// </summary>
        [Required(ErrorMessage = "The field BarCode is required")]
        [StringLength(16, ErrorMessage = "Tje fiel BarCode must have max length of 16 Characteres")]
        public string BarCode { get; set; }

        /// <summary>
        /// It is the department in which the product is
        /// </summary>
        [ForeignKey("Department")]
        [Required(ErrorMessage = "The fiel DepartmentId is required")]
        [Range(0, int.MaxValue, ErrorMessage = "the field DepartmentId must be a number")]
        public int DepartmentId { get; set; }
        public Department Department { get; set; }

        /// <summary>
        /// It is the cost at which you buy the product
        /// </summary>
        public decimal Cost { get; set; }

        /// <summary>
        /// It is the profit generated by the product
        /// </summary>
        public int Ganancia { get; set; }

        /// <summary>
        /// It is the price at which the product is sold
        /// </summary>
        [Required(ErrorMessage = "The field Price is required")]
        public decimal Price { get; set; }

        /// <summary>
        /// It is the current quantity of the product
        /// </summary>
        [Required(ErrorMessage = "The field Current_Quantity is required")]
        public int Current_Quantity { get; set; }

        /// <summary>
        /// It is the relationship between the DetailSales table and the Product table
        /// </summary>
        public virtual ICollection<DetailSale> DetailSales { get; set; }

    }
}
